// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLDscU9uZXJCKwNkhZ4HiBnoIgxunHjxs',
    appId: '1:532280069464:web:266d247eec4931fd8ee92d',
    messagingSenderId: '532280069464',
    projectId: 'change-it-1f85e',
    authDomain: 'change-it-1f85e.firebaseapp.com',
    storageBucket: 'change-it-1f85e.appspot.com',
    measurementId: 'G-4GYQ2LH64D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtAKA2bWLFq8HaCcePpmqyoCT5evHmWHA',
    appId: '1:532280069464:android:760ba30edf0c707d8ee92d',
    messagingSenderId: '532280069464',
    projectId: 'change-it-1f85e',
    storageBucket: 'change-it-1f85e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqkhrKzAXeVh77m7AV350_NssEAhYoZOQ',
    appId: '1:532280069464:ios:2b7068b4c16c75e68ee92d',
    messagingSenderId: '532280069464',
    projectId: 'change-it-1f85e',
    storageBucket: 'change-it-1f85e.appspot.com',
    iosClientId: '532280069464-l1readfgm3t451a07q3ltsgjoqthlhh7.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqkhrKzAXeVh77m7AV350_NssEAhYoZOQ',
    appId: '1:532280069464:ios:2b7068b4c16c75e68ee92d',
    messagingSenderId: '532280069464',
    projectId: 'change-it-1f85e',
    storageBucket: 'change-it-1f85e.appspot.com',
    iosClientId: '532280069464-l1readfgm3t451a07q3ltsgjoqthlhh7.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
